fysis/Fysis/Fysis/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', view=include('apps.inicio.urls' ,namespace="inicio")),
    url(r'^partida/', view=include('apps.partida.urls', namespace="partida")),
    #url(r'^crear_partida/', view=include('apps.partida.urls', namespace="crear_partida")),
    #url(r'^conectar_partida/', view=include('apps.partida.urls', namespace="conectar_partida")),
]

fysis/Fysis/apps/inicio/urls.py
from django.conf.urls import url, include 
from .views import inicio, conectarUsuario, ultimousuario


urlpatterns = [
	url(r'^$', inicio, name='inicio'),
	url(r'^unirse/', conectarUsuario, name='conectarUsuario'),
	url(r'^lleno/', ultimousuario, name='ultimousuario'),

]

fysis/Fysis/apps/partida/urls.py
from django.conf.urls import url
from .views import esperarPartida

urlpatterns = [
	url(r'^esperando_amigos/$',esperarPartida,name="esperarPartida"),
] 

fysis/Fysis/apps/inicio/models.py
from django.db import models
from django.template.defaultfilters import slugify


class Partida(models.Model):
    pin = models.CharField(primary_key = True, max_length = 15)
    fase = models.CharField(max_length = 30)
    resultado = models.CharField(max_length = 30)
    estado = models.BooleanField(blank=True)

    def save(self, *args, **kwargs):
        super(Partida, self).save(*args, **kwargs)
    
    def __str__(self):
        return (self.pin)

class Rol(models.Model):
    idRol = models.CharField(primary_key = True, max_length = 15)
    nombre = models.CharField(max_length = 15)

    def save(self, *args, **kwargs):

        super(Rol, self).save(*args, **kwargs)

    def __str__(self):
        return (self.nombre)

class Jugador(models.Model):
    #El id es el generado automáticamente por Django 
    nick = models.CharField(max_length = 15)
    estado = models.BooleanField()
    rol = models.ForeignKey('Rol')
    partida = models.ForeignKey('Partida')

    def save(self, *args, **kwargs):

        super(Jugador, self).save(*args, **kwargs)

    def __str__(self):
        return (self.nick)

     # Llama al "verdadero" método save().

fysis/Fysis/apps/partida/models.py
from django.db import models

# Create your models here.

fysis/Fysis/apps/inicio/forms.py
from django import forms
from .models import Jugador

class form_jugador(forms.ModelForm):
	pin = forms.CharField(max_length = 15)
	class Meta:
		model = Jugador
		fields = ['nick',]

fysis/Fysis/apps/inicio/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView
from .models import Partida
from .models import Jugador
from .models import Rol
from .forms import form_jugador
import random

def inicio(request):
	pin = random.randint(1,1000)
	while Partida.objects.filter(pin=pin).exists():
			pin = random.randint(1,1000)
	new_pin = Partida.objects.create(pin=pin, fase='dia', resultado='jugando', estado=True)

	ctx={}
	ctx['formato_jugador'] = form_jugador()
	ctx['pin'] = pin
	return render(request, 'inicio/inicio.html',ctx)

def conectarUsuario(request):
	roles = Rol.objects.get(idRol= '1')
	nuevo_jugador = form_jugador(request.POST)
	if nuevo_jugador.is_valid() :

		if Jugador.objects.filter(partida=nuevo_jugador.cleaned_data['pin']).count() <= 10: #Pregunta si la cantidad de jugadores de una partida es menor o igual a 10

			
				partida = Partida.objects.get(pin=nuevo_jugador.cleaned_data['pin'])
				Jugador.objects.create(nick=nuevo_jugador.cleaned_data['nick'], estado=True, rol=roles, partida=partida)
				return redirect('partida:esperarPartida')
			
		else:
			ctx = {}
			ctx['informe'] = 'PARTIDA LLENA'
			return render(request, 'inicio/inicio.html', ctx)
	else:
		ctx={}
		ctx['formato_jugador'] = nuevo_jugador
		return render(request, 'inicio/inicio.html', ctx)

def ultimousuario(request):
	if request . method == 'POST' :
		data = 'Prueba'

	return HttpResponse ( json.dumps ( data ))

fysis/Fysis/apps/partida/views.py
from django.shortcuts import render
from django.http import HttpResponse 
# Create your views here.

def esperarPartida(request):

	return render(request,'conectarPartida/esperarPartida.html')

fysis/Fysis/templates/CrearPartida/crearPartida.html
{% load staticfiles %}
<html lang="es">
<head>
	<meta charset="UTF-8">
	<title>CrearPartida</title>
	<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
	<link rel="shortcut icon" href="{% static 'css/images/ICONO_APP.png' %}" type="image/png">
	<!-- Latest compiled and minified CSS -->
	
	<link type="text/css" rel="stylesheet" href="{% static 'css/ultimaapp.css' %}"/>
	<script type="text/javascript">
	function desplegar(_valor){
		document.getElementById("backgroundVentana").style.visibility=_valor;
	}
	</script>
	
</head>
<body class="fondo">
<div class="row">
	<div class="col-xs-2">
		<a class="btn btn-default" type="button" href="#" style="padding-top:10px;padding-left:10px;">
		<img src="{% static 'css/images/AJUSTES.png' %}" width="50" height="50">
		</a><br>
		<a class="btn btn-default" type="button" href="#" style="padding-top:10px;padding-left:10px;">
		<img src="{% static 'css/images/INFO.png' %}" width="50" height="50">
		</a>
	</div>
	<div class="col-xs-8">
	<button><a href="javascript:desplegar('visible');">Desplegar</a></button>
		<div id="backgroundVentana">
			<div id= "ventana">
				<a href="javascript: desplegar('hidden');"><img src="{% static 'css/images/CERRAR.png' %}" alt="" class="Exit" width="50" height="50"></a>
					<div id="contenido">
						<input type="text" class="form-control" width="100">
						<a class="btn btn-default pin" type="button" href="#"><img src="{% static 'css/images/GENERAR_PIN.png' %}" width="170" height="80"></a>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
</body>
</html>

fysis/Fysis/templates/conectarPartida/conectarPartida.html
{% load staticfiles %}
<html lang="es">
<head>
	<meta charset="UTF-8">
	<title>Fysistencia</title>
	<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
	<link rel="shortcut icon" href="{% static 'css/images/ICONO_APP.png' %}" type="image/png">
	<!-- Latest compiled and minified CSS -->
	
	<link type="text/css" rel="stylesheet" href="{% static 'css/ultimaapp.css' %}"/>
	

	<script type="text/javascript">
	function iniciarpartida(_valor){
		document.getElementById("backgroundVentana").style.visibility=_valor;
	}
	function unirse(_valor){
		document.getElementById("backgroundVentana2").style.visibility=_valor;
	}
	function info(_valor){
		document.getElementById("backgroundVentana3").style.visibility=_valor;
	}
	</script>
	
</head>

<body class="fondo">

<div class="row">
	<div class="col-xs-4">
		<a class="btn btn-default" type="button" href="#" style="padding-top:10px;padding-left:10px;">
		<img src="{% static 'css/images/AJUSTES.png' %}" width="50" height="50">
		</a><br>
		<a class="btn btn-default" type="button"  href="javascript:info('visible');" style="padding-top:10px;padding-left:10px;">
		<img src="{% static 'css/images/INFO.png' %}" width="50" height="50">
		</a>
		
	</div>
  	<div class="col-xs-8">
  	<center><br><br><br>
	  		<a class="btn btn-default" type="button" href="javascript:iniciarpartida('visible');"><img src="{% static 'css/images/INICIAR_PARTIDA.png' %}" width="200" height="110"></a>
	  		<br>
	  		<a class="btn btn-default" type="button"  href="javascript:unirse('visible');"><img src="{% static 'css/images/UNIRSE.png' %}" width="200" height="110"></a>
	  		<div id="backgroundVentana">
				
				<div id= "ventana">
					<a href="javascript: iniciarpartida('hidden');"><img src="{% static 'css/images/CERRAR.png' %}" alt="" class="Exit img-responsive" width="50" height="50"></a>
					

					<div id="formulario">
						<input type="text" class="img-responsive form-control" width="100"  placeholder="Introduce tu Nick">
						
					</div>
					<div id="siguiente">
						<a class="btn btn-default pin" type="button" href="#"><img src="{% static 'css/images/GENERAR_PIN.png' %}" class="img-responsive" width="170" height="80"></a>
					</div>	


				</div>
			</div>
			<div id="backgroundVentana2">
				
				<div id= "ventana2">
					<a href="javascript: unirse('hidden');"><img src="{% static 'css/images/CERRAR.png' %}" alt="" class="Exit img-responsive" width="50" height="50"></a>
					<div id="formulario">
						<input type="password" class="img-responsive form-control" width="100" placeholder="Introduce el PIN">
	
					</div>
					<div id="siguiente">
						<a class="btn btn-default pin" type="button" href="#"><img src="{% static 'css/images/INGRESAR.png' %}" class="img-responsive" width="170" height="80"></a>
					</div>	


				</div>
			</div>
			<div id="backgroundVentana3">
				
				<div id= "ventana3">
					<a href="javascript: info('hidden');"><img src="{% static 'css/images/CERRAR.png' %}" alt="" class="Exit img-responsive" width="50" height="50"></a>
					

					<div id="contenido">
						<a href="#"><img src="{% static 'css/images/HISTORIA.png' %}"  alt=""  class="img-responsive"></a>
						<a href="#"><img src="{% static 'css/images/REGLAS.png' %}"  alt="" class="img-responsive"></a>
						<a href="#"><img src="{% static 'css/images/QUE_HAGO.png' %}"  alt="" class="img-responsive"></a>
					</div>


				</div>
			</div>
			
	</center>
	</div>
</div>


</body>
</html>

fysis/Fysis/templates/conectarPartida/esperarPartida.html
{% load staticfiles %}
<html lang="es">
<head>
	<meta charset="UTF-8">
	<title>Fysistencia</title>
	<meta name="viewport" content="width=device-width, user-scalable=yes, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
	<link rel="shortcut icon" href="{% static 'images/ICONO_APP.png' %}" type="image/png">
	<link href="https://fonts.googleapis.com/css?family=Alegreya+Sans" rel="stylesheet"> 

	<!-- Latest compiled and minified CSS -->
	
	<link type="text/css" rel="stylesheet" href="{% static 'css/esperarPartida.css' %}"/>

	<style type="text/css">
		import url('https://fonts.googleapis.com/css?family=Alegreya+Sans');
	</style>

	
</head>
<body class="fondo">
<div id="US1">
	<img src="{% static 'images/USUARIO_PANTALLA_DE_ESPERA.png' %}"class="img-responsive" >
</div>
<div id="NAME">
	<img src="{% static 'images/NOMBRE_USUARIO.png' %}"class="img-responsive" >
</div>

</body>
</html>

fysis/Fysis/templates/inicio/inicio.html
{% load staticfiles %}
{% load static %}
<html lang="es">
<head>
	<meta charset="UTF-8">
	<title>Fysistencia</title>
	<meta name="viewport" content="width=device-width, user-scalable=yes, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
	<link rel="shortcut icon" href="{% static 'images/ICONO_APP.png' %}" type="image/png">
	<link href="https://fonts.googleapis.com/css?family=Alegreya+Sans" rel="stylesheet"> 

	<!-- Latest compiled and minified CSS -->
	
	<link type="text/css" rel="stylesheet" href="{% static 'css/main.css' %}"/>
	
	<!-- link para JS -->
	<script type="text/javascript" src="{% static 'js/inicio.js' %}"></script>

	<style type="text/css">
		import url('https://fonts.googleapis.com/css?family=Alegreya+Sans');
	</style>

	<script src={% static  'jquery-3.1.1.min.js' %} type="text/javascript"></script>

	<script type="text/javascript">

		$('#verficar_partida').click(function(){ 
			$.ajax({

					data:{'id':2, 'partida':10},
					url : "{% url 'inicio:ultimousuario' %}",
					type : 'post',
					cache : false,
					success : function(data){ 

						alert("PARTIDA LLENA");
					}





				})
				}
			)	

	</script>

</head>

<body class="fondo">
<div id="fysis">
	<img src="{% static 'images/ISOLOGOTIPO_JUEGO.png' %}"class="img-responsive" >
</div>
<div class="row">
	<div class="col-xs-4">

		<!-- 	Botón Configuración    -->
		<a class="btn btn-default" type="button" href="javascript:config('visible');" style="padding-top:5%;padding-left:10%;">
		<img src="{% static 'images/AJUSTES.png' %}" class="img-responsive" width="50" height="50">
		</a><br>

		<!-- 	Botón Info    -->
		<a class="btn btn-default" type="button"  href="javascript:info('visible');" style="padding-top:5%;padding-left:10%;">
		<img src="{% static 'images/INFO.png' %}"class="img-responsive" width="50" height="50">
		</a>
		
	</div>
  	<div id="btn1">
  	<center><br>
	  		<a class="btn btn-default" type="button" href="javascript:iniciarpartida('visible');"><img src="{% static 'images/INICIAR_PARTIDA.png' %}" class="img-responsive" width="220" height="130"></a>
	</center>
	</div>
	<div id="btn2">
	<center>
		<a class="btn btn-default" type="button"  href="javascript:unirse('visible');"><img src="{% static 'images/UNIRSE.png' %}" class="img-responsive" width="220" height="130"></a>
	</center>
	</div>  		
	  		



<!-- 	ventana INICIAR INICIAR    -->
	  		<div id="backgroundVentana">
				<div id= "ventana">
					<a href="javascript: iniciarpartida('hidden');"><img src="{% static 'images/CERRAR.png' %}" alt="" class="Exit img-responsive" width="50" height="50"></a>

					<h1 id="pinNum">{{pin}}</h1>
					<div id="formularioCrear">

						<input type="text" class="img-responsive form-control" width="100"  placeholder="Introduce tu Nick">
						
					</div>
					<div id="siguiente">
						<a class="btn btn-default pin" type="button" href="#"><img src="{% static 'images/GENERAR_PIN.png' %}" class="img-responsive" width="170" height="80"></a>
					</div>	
				</div>
			</div>
<!-- 	FIN ventana INICIAR PARTIDA    -->



<!-- 	ventana UNIRSE    -->
			<div id="backgroundVentana2">
				
				<div id= "ventana2">
					<a href="javascript: unirse('hidden');"><img src="{% static 'images/CERRAR.png' %}" alt="" class="Exit img-responsive" width="50" height="50"></a>
					<div id="formulario">
						{% if informe == "PARTIDA LLENA" %}
							
							<div id="destino"></div>

						{%else%}
							<form method="post" action="{% url 'inicio:conectarUsuario' %}" enctype="multipart/form-data">{% csrf_token %}
								{{formato_jugador.as_p}}
								<button id="verficar_partida"  style="color:#0000">CONECTAR</button>
							</form>
						{% endif %}
					</div>
					<div id="siguiente">
						<a class="btn btn-default pin" type="button" href="{% url 'partida:esperarPartida' %}"><img src="{% static 'images/INGRESAR.png' %}" class="img-responsive" width="170" height="80"></a>
					</div>	


				</div>
			</div>
<!-- 	FIN ventana UNIRSE    -->


<!-- 	Ventana Configuración    -->
	<div id="backgroundVentanaConfig">
		<div id= "ventanaConfig">
			<a href="javascript: config('hidden');"><img src="{% static 'images/CERRAR.png' %}" alt="" class="Exit img-responsive" width="50" height="50"></a>
			<div id="contenidoConfig">
				<a href="#" id= "prueba"><img src="{% static 'images/botonVacio.png' %}" alt=""  class="img-responsive" width="324" height="86"></a>
				<a href="#"><img src="{% static 'images/botonVacio.png' %}"alt="" class="img-responsive"width="324" height="86"></a>
				<a href="#"><img src="{% static 'images/botonVacio.png' %}" alt="" class="img-responsive"width="324" height="86"></a>
			</div>
		</div>
	</div>
<!-- 	Fin ventana Configuración    -->


<!-- 	ventana AYUDA    -->
			<div id="backgroundVentana3">
				
				<div id= "ventana3">
					<a href="javascript: info('hidden');"><img src="{% static 'images/CERRAR.png' %}" alt="" class="Exit img-responsive" width="50" height="50"></a>
					

					<div id="contenido">
						<!-- 	HISTORIA    -->
						<a href="javascript:historia('visible'),info('hidden');"><img src="{% static 'images/HISTORIA.png' %}"  alt=""  class="img-responsive"></a>
							<!-- 	DESPLEGABLE HISTORIA    -->
							<div id="backgroundVentana4">
								<div id= "ventana4">
									<a href="javascript: historia('hidden');"><img src="{% static 'images/CERRAR.png' %}" alt="" class="Exit img-responsive" width="50" height="50"></a>
									<div id="contenido2">
										<div id="siguiente2">
											<div id="scroll">
												<h5 class="texto">Con un historial de tragedia y contaminación, Fysistencia ha superado su pasado dando lugar a una ciudad mas alegre y ecológica.
											En él habita un arbol misterioso que al caer la noche se abren entre sus ramas lobizones con el objetivo de conquistar al pueblo y apoderarse de sus territorios. Pero la ciudad no está indefenza, por lo que cazadores velan para proteger a su habitantes con la ayudade un médico naturista. Y es ahí donde la diversión comienza, Fysis te guará por una aventura en la que tendrás que valerte e tus propios instintos y al amanecer, veremos quién reina en el pueblo, ¿Estas listo?</h5>
											</div>
										</div>
									</div>
								</div>
							</div>
							<!-- 	FIN DESPLEGABLE HISTORIA    -->
						<!-- 	FIN HISTORIA    -->
						<!-- 	REGLAS    -->
						<a href="javascript:reglas('visible'),info('hidden')"><img src="{% static 'images/REGLAS.png' %}"  alt="" class="img-responsive"></a>
							<!-- 	DESPLEGABLE REGLAS    -->
							<div id="background-ventana-reglas">
								<div id= "ventana-reglas">
									<a href="javascript: reglas('hidden');"><img src="{% static 'images/CERRAR.png' %}" alt="" class="Exit img-responsive" width="50" height="50"></a>
									<div id="contenido2">
										<div id="siguiente2">
											<div id="scroll" >
												<h5 class="texto">Las reglas del juego:
Fysis es un juego de rol basado en el clásico juego “Mafia” pero adaptado a nuestra región del nea, en formato web para dispositivos móviles.
El objetivo del juego es recrear un escenario ficticio en donde sos un personaje de la ciudad Fysistencia. En ella existen dos bandos, uno bueno formado por cazadores, un curandero y el resto de la ciudad denominado “pueblo” .  El otro bando de los malos está formado por lobizones.
Los lobizones conocen la identidad de los demás lobizones, pero desconocen la de los otros jugadores, lo mismo se aplica para los cazadores saben solamente quien mas es cazador pero no la del resto de los participantes.
El pueblo y curandero solo conoce su identidad y ninguna más.
La partida del juego transcurre a través de 3 fases: nocturna, diurna y debate. 




HABILIDADES DE CADA ROL
Aplicación moderador: dirige el juego, cuenta la historia y relata los hechos ocurridos en la fase nocturna.
Lobizon(s): si son mas de uno, deben ponerse de acuerdo mediante señas para elegir una víctima.
Cazador(s): debe elegir algún jugador que sospeche que podría ser lobizón.
Curandero: debe elegir algún jugador que piense que podría haber sido asesinado para salvarlo. 
Pueblo: son el resto de jugadores que desconoce el rol de los demás participantes, su participación durante la fase nocturna es pasiva, no deben hacer nada más que mantener los ojos cerrados.


FASES DEL JUEGO
FASE DIURNA:
La primera vez que se ejecuta esta etapa la aplicación relatara una introducción sobre el lugar donde viven los personajes y los invitara a que cierren los ojos para dormir porque se acerca la noche.
FASE NOCTURNA:
1 turno: Lobizones.
Cuando cae la noche la aplicación pedirá a los lobizones que se despierten y que seleccionen a su víctima, deberán ponerse de acuerdo mediante señas. 
 En la pantalla verán un mapa del juego con los nombres de los jugadores, resaltado quienes son los demás lobizones.
Para elegir una víctima solo deben seleccionarla del mapa, si coinciden todos los lobizones se les ordena cerrar los ojos de nuevo.
2 turno: Cazadores.
Se solicita que se despierten y seleccionen a un sospechoso de ser lobizón, deberán ponerse de acuerdo mediante señas.
En la pantalla verán un mapa del juego con los nombres de los jugadores, resaltado quienes son los demás cazadores.
Para elegir un sospechoso solo deben seleccionarla del mapa, si coinciden todos los cazadores la aplicación les informará si es o no un lobizón, luego se les ordena cerrar los ojos de nuevo.
3 turno: Curandero.
La aplicación pide que se despierte el curandero. En la pantalla verá un mapa del juego con los nombres de los demás jugadores. Deberá seleccionar a uno para salvarlo sin saber si fue atacado o no, luego se le ordena cerrar los ojos de nuevo.

2 FASE DIURNA 
Durante esta segunda fase diurna la aplicación relatara los hechos ocurridos durante la noche que dependen de las acciones de los jugadores.
Si la persona que atacaron los lobizones no fue la salvada por el curandero, contara que alguien fue asesinado y revelara la identidad de la víctima, esta persona queda fuera del juego a partir de la siguiente fase nocturna.
Si la persona que eligieron los lobizones fue la salvada por el curandero, contará que alguien fue atacado pero que el curandero lo salvó, no revelara la identidad de nadie.
Si la persona que eligieron los cazadores era un lobizón, contará que se conoce la identidad de un lobizón, pero no revelara la identidad de nadie.
Si la persona que eligieron los cazadores no era un lobizón, contará que no se conoce la identidad del asesino, y no revelara nada más.

FASE DEBATE: 
Esta fase se basa en deducción y engaño, los jugadores debaten sobre quién creen que es sospechoso para al final votar. La persona con mas votos va a la horca.
En esta etapa se puede mentir para convencer a los demás de votar por alguien y seguir en juego.</h5>
											</div>
										</div>
									</div>
								</div>
							</div>
							<!-- 	FIN DESPLEGABLE REGLAS    -->
						<!-- 	FIN REGLAS    -->
						<!-- 	QUE HAGO    -->
						<a href="#"><img src="{% static 'images/QUE_HAGO.png' %}"  alt="" class="img-responsive"></a>
						<!-- 	FIN QUE HAGO    -->
					</div>


				</div>
			</div>
	</center>
	</div>
</div>


</body>
</html>